### ISSUE TITLE
code license

### ISSUE THREAD

**Issue by stefano77it** [hartleybrody/public-amazon-crawler#1]
Hi,
I searched in the repository, but nowhere I found a License file or a note about the license of the code.

What is the license of public-amazon-crawler ?

Thanks

**Comment by hartleybrody** [comment]
Hey Stefano,

Hmm, I haven't thought about what sort of license I'd want to put on it yet. Can I ask what sort of project you're planning to use it for? If you'd prefer a more private discussion, shoot me [a note on here](https://blog.hartleybrody.com/contact-me/) and we'll get it all figured out!
