### ISSUE TITLE
WARNING 503 from Amazon and WARNING No URLs found in the queue

### ISSUE THREAD

**Issue by Marow** [hartleybrody/public-amazon-crawler#11]
Most time i get now 503 WARNINGS...

Why is that? I need more Proxies or something?
Any amount recommended or something? why get so much 503 now... before much hours it works fine

And i get much time 
`WARNING: No URLs found in the queue. Retrying...`
But i dont know why

**Comment by hartleybrody** [comment]
I can only offer support on the code itself. In terms of how you're using it to scrape amazon, I have no idea how many requests you're making, or how quickly, or why they're sending you specific responses.

You'll have to do some of your own troubleshooting for that.

**Comment by Marow** [comment]
Okay understand...

Do you have some Proxy lists or something there free? Found http://pubproxy.com/ but i dont know, that is not working
