### ISSUE TITLE
Amazon returns blank pages.

### ISSUE THREAD

**Issue by lagodinm** [hartleybrody/public-amazon-crawler#20]
Amazon returns blank pages. This has been happening as of late. I've tried from different proxies, in 1 thread, with different headers. However, on the same request built through CURL it returns as it should. What may be the reason
![pic](https://user-images.githubusercontent.com/59138339/172603196-19443ba0-1960-4058-a758-d94e91b0f683.png)
?

**Comment by hartleybrody** [comment]
If you're getting a different response in your browser and your web scraping program, then you're not making the exact same request. It could be you're not setting headers or cookies, it could be that you're making the request through different IPs and one has been blocked.

Try having your scraping code visit a site like https://httpbin.org/ and see what your requests look like from the server's side, that should help you see if anything is missing.

**Comment by lagodinm** [comment]
Hi Hartley! I previously checked everything with https://lumtest.com/echo.json. Just checked with httpbin: headers are identical up to every character...ip address is the same, no cookies...CURL returns data-asin and s-result-item, but public-crawler does not return them. I'm at a loss as to how this can happen? The start url is the same too. One only suspicion is that curl loads additional content automatically (like Amazon control pixel) and public-crawler doesn't. What do you think about it? 
CURL gets [s-result-item]:
`curl 'https://www.amazon.com/s?i=amazonbasics&srs=10112675011&rh=n:10112675011&fs=true&ref=lp_10112675011_sar' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: deflate, br'`
Public-Crawler - no [s-result-item]:
```
...
# Redis
redis_host = "127.0.0.1"
redis_port = 6379
redis_db = 0

# Request
headers = {
#   "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Accept-Encoding": "deflate, br",
    "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0",
}

allowed_params = ["node", "rh", "page", "i", "bbn", "k"]
...
```

![CURL](https://user-images.githubusercontent.com/59138339/172681623-5c5cfa4b-7e1a-4a80-8bab-6f373270cb58.png)
![crawler](https://user-images.githubusercontent.com/59138339/172681653-5ff8e4a5-b5f2-48ad-b8c7-fb1eeae3d64c.png)

**Comment by lagodinm** [comment]
@hartleybrody figured it out. Because of the restrictions in the parameter string, an incomplete url was made.
```
allowed_params = ["node", "rh", "page", "i", "bbn", "k", "srs", "fs", "ref"]
#allowed_params = ["node", "rh", "page"]
```

**Comment by hartleybrody** [comment]
Ah, good to know! What was the necessary query argument that was getting filtered out?

You could add it to that list in a pull request and I'll approve it 👍

**Comment by lagodinm** [comment]
@hartleybrody,
I have included as many parameters as possible so far. 
There is a suggestion that amazon bans more often if you don't use optional parameters like ref in the url. I don't know if that's right yet. Also trying to do something about the 400 page limit so I don't lose a lot of asins in the listings. It would also be nice if Crawler handled all category levels, not just the ones on starturls. Do you think it's already possible to send a pull request?

**Comment by vnikifirov** [comment]
Hello @lagodinm. I believe that is a problem with JavaScript (frontend or clientside) logic and could be problem with http headers. As I believe Amazon is SPA application, I can see Amazon page doesn't pull list of products from server or DataBase. I have Amazon account and everything is working for me. You can see search result on the image, but I have other problem. My problem is my account is locked Amazon wants me to reach our them by phone that is too expensive for me cos I'm not in USA.


<img width="809" alt="search result of lodine" src="https://user-images.githubusercontent.com/39588115/173085751-e6d528e1-2b6f-4dea-82c3-97ac5aa84b91.png">
