### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by staticabhi** [hartleybrody/public-amazon-crawler#3]
Hey,

I'm getting system error @ "print "{}: {}".format(datetime.now(), msg)" in helpers.

**Comment by hartleybrody** [comment]
You might be using python 3? If so, the syntax for that line should read:

`print("{}: {}".format(datetime.now(), msg))`

Let me know if that works!

**Comment by staticabhi** [comment]
Hey, Yes.. it resolved the issue.. thanks for help!
