### ISSUE TITLE
Amazon link structure changed (?)

### ISSUE THREAD

**Issue by mpekalski** [hartleybrody/public-amazon-crawler#7]
Looks like Amazon has changed structure of links a bit, as the crawler fails to run:

```
Traceback (most recent call last):
  File "crawler.py", line 98, in <module>
    begin_crawl()  # put a bunch of subcategory URLs into the queue
  File "crawler.py", line 42, in begin_crawl
    enqueue_url(link)
  File "/tmp/public-amazon-crawler/helpers.py", line 104, in enqueue_url
    url = format_url(u)
  File "/tmp/public-amazon-crawler/helpers.py", line 67, in format_url
    k, v = piece.split("=")
ValueError: too many values to unpack
```

**Comment by hartleybrody** [comment]
Can you provide the URL you were trying to crawl? Seems like it might've been a query string value that had an un-escaped equals sign:

```
a, b = "a=b=c".split("=")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: too many values to unpack
```

**Comment by mpekalski** [comment]
I have just tried to run the code pulled from your repository and it complained about the above. I guess amazon redirects now from the links you have provided in start-urls.txt

Anyway, I made a quick fix
https://github.com/mpekalski/public-amazon-crawler/commit/55585c835b0a756e631e4667a1f8d469be176992

although I am not sure if it is correct form tracking (by Amazon) point of view.
